/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     http://www.apache.org/licenses/LICENSE-2.0
/// 
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 0x10000049 generated on 2025-07-01 22:57:25.872972
/// To compile with gcc:
///     gcc -lstdc++ ik.cpp
/// To compile without any main function as a shared object (might need -llapack):
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp
#define IKFAST_HAS_LIBRARY
#include "ikfast.h" // found inside share/openrave-X.Y/python/ikfast.h
using namespace ikfast;

// check if the included ikfast version matches what this file was compiled with
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
IKFAST_COMPILE_ASSERT(IKFAST_VERSION==0x10000049);

#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>

#ifndef IKFAST_ASSERT
#include <stdexcept>
#include <sstream>
#include <iostream>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI  ((IkReal)6.28318530717959)
#define IKPI  ((IkReal)3.14159265358979)
#define IKPI_2  ((IkReal)1.57079632679490)

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#ifndef isinf
#define isinf _isinf
#endif
//#ifndef isfinite
//#define isfinite _isfinite
//#endif
#endif // _MSC_VER

// lapack routines
extern "C" {
  void dgetrf_ (const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
  void zgetrf_ (const int* m, const int* n, std::complex<double>* a, const int* lda, int* ipiv, int* info);
  void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
  void dgesv_ (const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
  void dgetrs_(const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info);
  void dgeev_(const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi,double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info);
}

using namespace std; // necessary to get std math routines

#ifdef IKFAST_NAMESPACE
namespace IKFAST_NAMESPACE {
#endif

inline float IKabs(float f) { return fabsf(f); }
inline double IKabs(double f) { return fabs(f); }

inline float IKsqr(float f) { return f*f; }
inline double IKsqr(double f) { return f*f; }

inline float IKlog(float f) { return logf(f); }
inline double IKlog(double f) { return log(f); }

// allows asin and acos to exceed 1. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_SINCOS_THRESH
#define IKFAST_SINCOS_THRESH ((IkReal)1e-7)
#endif

// used to check input to atan2 for degenerate cases. has to be smaller than thresholds used for branch conds and evaluation
#ifndef IKFAST_ATAN2_MAGTHRESH
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)1e-7)
#endif

// minimum distance of separate solutions
#ifndef IKFAST_SOLUTION_THRESH
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#endif

// there are checkpoints in ikfast that are evaluated to make sure they are 0. This threshold speicfies by how much they can deviate
#ifndef IKFAST_EVALCOND_THRESH
#define IKFAST_EVALCOND_THRESH ((IkReal)0.00001)
#endif


inline float IKasin(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(-IKPI_2);
else if( f >= 1 ) return float(IKPI_2);
return asinf(f);
}
inline double IKasin(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asin(f);
}

// return positive value in [0,y)
inline float IKfmod(float x, float y)
{
    while(x < 0) {
        x += y;
    }
    return fmodf(x,y);
}

// return positive value in [0,y)
inline double IKfmod(double x, double y)
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}

inline float IKacos(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(IKPI);
else if( f >= 1 ) return float(0);
return acosf(f);
}
inline double IKacos(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0;
return acos(f);
}
inline float IKsin(float f) { return sinf(f); }
inline double IKsin(double f) { return sin(f); }
inline float IKcos(float f) { return cosf(f); }
inline double IKcos(double f) { return cos(f); }
inline float IKtan(float f) { return tanf(f); }
inline double IKtan(double f) { return tan(f); }
inline float IKsqrt(float f) { if( f <= 0.0f ) return 0.0f; return sqrtf(f); }
inline double IKsqrt(double f) { if( f <= 0.0 ) return 0.0; return sqrt(f); }
inline float IKatan2Simple(float fy, float fx) {
    return atan2f(fy,fx);
}
inline float IKatan2(float fy, float fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return float(IKPI_2);
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2f(fy,fx);
}
inline double IKatan2Simple(double fy, double fx) {
    return atan2(fy,fx);
}
inline double IKatan2(double fy, double fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2(fy,fx);
}

template <typename T>
struct CheckValue
{
    T value;
    bool valid;
};

template <typename T>
inline CheckValue<T> IKatan2WithCheck(T fy, T fx, T epsilon)
{
    CheckValue<T> ret;
    ret.valid = false;
    ret.value = 0;
    if( !isnan(fy) && !isnan(fx) ) {
        if( IKabs(fy) >= IKFAST_ATAN2_MAGTHRESH || IKabs(fx) > IKFAST_ATAN2_MAGTHRESH ) {
            ret.value = IKatan2Simple(fy,fx);
            ret.valid = true;
        }
    }
    return ret;
}

inline float IKsign(float f) {
    if( f > 0 ) {
        return float(1);
    }
    else if( f < 0 ) {
        return float(-1);
    }
    return 0;
}

inline double IKsign(double f) {
    if( f > 0 ) {
        return 1.0;
    }
    else if( f < 0 ) {
        return -1.0;
    }
    return 0;
}

template <typename T>
inline CheckValue<T> IKPowWithIntegerCheck(T f, int n)
{
    CheckValue<T> ret;
    ret.valid = true;
    if( n == 0 ) {
        ret.value = 1.0;
        return ret;
    }
    else if( n == 1 )
    {
        ret.value = f;
        return ret;
    }
    else if( n < 0 )
    {
        if( f == 0 )
        {
            ret.valid = false;
            ret.value = (T)1.0e30;
            return ret;
        }
        if( n == -1 ) {
            ret.value = T(1.0)/f;
            return ret;
        }
    }

    int num = n > 0 ? n : -n;
    if( num == 2 ) {
        ret.value = f*f;
    }
    else if( num == 3 ) {
        ret.value = f*f*f;
    }
    else {
        ret.value = 1.0;
        while(num>0) {
            if( num & 1 ) {
                ret.value *= f;
            }
            num >>= 1;
            f *= f;
        }
    }
    
    if( n < 0 ) {
        ret.value = T(1.0)/ret.value;
    }
    return ret;
}

/// solves the forward kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void ComputeFk(const IkReal* j, IkReal* eetrans, IkReal* eerot) {
for(int dummyiter = 0; dummyiter < 1; ++dummyiter) {
IkReal x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22;
x0=IKsin(j[0]);
x1=IKsin(j[1]);
x2=IKsin(j[2]);
x3=IKcos(j[2]);
x4=IKcos(j[1]);
x5=IKsin(j[3]);
x6=IKcos(j[3]);
x7=IKcos(j[0]);
x8=((0.0611)*x0);
x9=((2.2e-7)*x0);
x10=((0.11257021)*x1);
x11=((0.13490002)*x0);
x12=((0.02799917)*x4);
x13=((2.2e-7)*x7);
x14=((1.0)*x7);
x15=((0.0051995)*x0);
x16=((0.0051995)*x7);
x17=((0.0611)*x7);
x18=((0.13490002)*x7);
x19=(x1*x3);
x20=(x1*x2);
x21=(x3*x4);
x22=(x2*x4);
IkReal x23=((1.0)*x21);
IkReal x24=((1.0)*x19);
IkReal x25=((1.0)*x22);
IkReal x26=((1.0)*x0);
eetrans[0]=((0.1207909)+((x6*(((((-1.0)*x23*x8))+((x20*x8))))))+(((-0.00017791)*x7))+(((-1.0)*x10*x26))+((x5*(((((-1.0)*x23*x9))+((x20*x9))))))+((x11*x20))+((x5*((((x22*x8))+((x19*x8))))))+((x6*(((((-1.0)*x25*x9))+(((-1.0)*x24*x9))))))+(((-1.0)*x11*x23))+(((-1.0)*x15*x25))+(((-1.0)*x15*x24))+(((-0.03039913)*x0))+(((-1.0)*x12*x26)));
IkReal x27=((1.0)*x19);
IkReal x28=((1.0)*x7);
IkReal x29=((1.0)*x13);
IkReal x30=((1.0)*x21);
eetrans[1]=((-0.0230745)+((x6*(((((-1.0)*x22*x29))+(((-1.0)*x13*x27))))))+((x18*x20))+((x5*(((((-1.0)*x21*x29))+((x13*x20))))))+(((-1.0)*x18*x30))+(((-1.0)*x16*x27))+((x5*((((x17*x19))+((x17*x22))))))+(((-1.0)*x16*x22))+(((-1.0)*x10*x28))+(((0.00017791)*x0))+((x6*((((x17*x20))+(((-1.0)*x17*x30))))))+(((-0.03039913)*x7))+(((-1.0)*x12*x28)));
eetrans[2]=((0.1490817)+((x6*(((((2.2e-7)*x21))+(((-2.2e-7)*x20))))))+(((-0.13490002)*x22))+((x6*(((((-0.0611)*x22))+(((-0.0611)*x19))))))+(((-0.13490002)*x19))+(((-0.0051995)*x20))+(((0.0051995)*x21))+(((-0.02799917)*x1))+((x5*(((((-2.2e-7)*x22))+(((-2.2e-7)*x19))))))+(((0.11257021)*x4))+((x5*(((((-0.0611)*x21))+(((0.0611)*x20)))))));
IkReal x31=((1.0)*x14);
if( ((((x5*(((((-1.0)*x22*x31))+(((-1.0)*x19*x31))))))+((x6*((((x21*x7))+(((-1.0)*x20*x31)))))))) < -1-IKFAST_SINCOS_THRESH || ((((x5*(((((-1.0)*x22*x31))+(((-1.0)*x19*x31))))))+((x6*((((x21*x7))+(((-1.0)*x20*x31)))))))) > 1+IKFAST_SINCOS_THRESH )
    continue;
eerot[0]=IKacos((((x5*(((((-1.0)*x22*x31))+(((-1.0)*x19*x31))))))+((x6*((((x21*x7))+(((-1.0)*x20*x31))))))));
return;
}
IKFAST_ASSERT(0);
}

IKFAST_API int GetNumFreeParameters() { return 1; }
IKFAST_API int* GetFreeParameters() { static int freeparams[] = {4}; return freeparams; }
IKFAST_API int GetNumJoints() { return 5; }

IKFAST_API int GetIkRealSize() { return sizeof(IkReal); }

IKFAST_API int GetIkType() { return 0x4400000c; }

class IKSolver {
public:
IkReal j0,cj0,sj0,htj0,j0mul,j1,cj1,sj1,htj1,j1mul,j2,cj2,sj2,htj2,j2mul,j3,cj3,sj3,htj3,j3mul,j4,cj4,sj4,htj4,new_r00,r00,rxp0_0,new_r01,r01,rxp0_1,new_r02,r02,rxp0_2,new_px,px,npx,new_py,py,npy,new_pz,pz,npz,pp;
unsigned char _ij0[2], _nj0,_ij1[2], _nj1,_ij2[2], _nj2,_ij3[2], _nj3,_ij4[2], _nj4;

IkReal j100, cj100, sj100;
unsigned char _ij100[2], _nj100;
bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
j0=numeric_limits<IkReal>::quiet_NaN(); _ij0[0] = -1; _ij0[1] = -1; _nj0 = -1; j1=numeric_limits<IkReal>::quiet_NaN(); _ij1[0] = -1; _ij1[1] = -1; _nj1 = -1; j2=numeric_limits<IkReal>::quiet_NaN(); _ij2[0] = -1; _ij2[1] = -1; _nj2 = -1; j3=numeric_limits<IkReal>::quiet_NaN(); _ij3[0] = -1; _ij3[1] = -1; _nj3 = -1;  _ij4[0] = -1; _ij4[1] = -1; _nj4 = 0; 
for(int dummyiter = 0; dummyiter < 1; ++dummyiter) {
    solutions.Clear();
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];

j4=pfree[0]; cj4=cos(pfree[0]); sj4=sin(pfree[0]);
r00 = eerot[0];
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];
new_px=px;
new_py=py;
new_pz=pz;
new_r00=r00;
r00 = new_r00; px = new_px; py = new_py; pz = new_pz;

pp=((px*px)+(py*py)+(pz*pz));
{
IkReal j0array[2], cj0array[2], sj0array[2];
bool j0valid[2]={false};
_nj0 = 2;
IkReal x32=((0.1207909)+(((-1.0)*px)));
IkReal x33=((0.0230745)+py);
CheckValue<IkReal> x36 = IKatan2WithCheck(IkReal(x32),IkReal(x33),IKFAST_ATAN2_MAGTHRESH);
if(!x36.valid){
continue;
}
IkReal x34=((1.0)*(x36.value));
if((((x32*x32)+(x33*x33))) < -0.00001)
continue;
CheckValue<IkReal> x37=IKPowWithIntegerCheck(IKabs(IKsqrt(((x32*x32)+(x33*x33)))),-1);
if(!x37.valid){
continue;
}
if( (((0.00017791)*(x37.value))) < -1-IKFAST_SINCOS_THRESH || (((0.00017791)*(x37.value))) > 1+IKFAST_SINCOS_THRESH )
    continue;
IkReal x35=IKasin(((0.00017791)*(x37.value)));
j0array[0]=((((-1.0)*x34))+x35);
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
j0array[1]=((3.14159265358979)+(((-1.0)*x35))+(((-1.0)*x34)));
sj0array[1]=IKsin(j0array[1]);
cj0array[1]=IKcos(j0array[1]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
if( j0array[1] > IKPI )
{
    j0array[1]-=IK2PI;
}
else if( j0array[1] < -IKPI )
{    j0array[1]+=IK2PI;
}
j0valid[1] = true;
for(int ij0 = 0; ij0 < 2; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 2; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

IkReal op[162], zeror[48];
int numroots;;
IkReal x38=IKsin(j0);
IkReal x39=IKcos(j0);
IkReal x40=((0.2415818)*px);
IkReal x41=((0.52330382)*pz);
IkReal x42=((0.046149)*py);
IkReal x43=((1.0)*pz);
IkReal x44=((-0.25645219)+pz);
IkReal x45=((-0.25645263)+pz);
IkReal x46=((0.2981634)+(((-2.0)*pz)));
IkReal x47=((0.07302298)*pz);
IkReal x48=((0.53960008)*pz);
IkReal x49=((0.04171121)+(((-1.0)*x43)));
IkReal x50=((0.04171077)+(((-1.0)*x43)));
IkReal x51=((0.01410796643094)*x38);
IkReal x52=((1.0)*(px*px));
IkReal x53=((1.0)*(py*py));
IkReal x54=(pz*x43);
IkReal x55=((1.0)*(IKcos(r00)));
IkReal x56=((0.1207909)*x38);
IkReal x57=((4.0)*x39);
IkReal x58=((0.2415818)*x38);
IkReal x59=((0.046149)*x39);
IkReal x60=((-0.5963268)+(((4.0)*pz)));
IkReal x61=((0.000579786656728)*x38);
IkReal x62=((0.000479903451)*x39);
IkReal x63=((0.0025122091382)*x38);
IkReal x64=((0.0230745)*x39);
IkReal x65=(px*x38);
IkReal x66=(py*x39);
IkReal x67=(x39+(((-1.0)*x55)));
IkReal x68=((-4.0)*x39);
IkReal x69=((2.0)*x65);
IkReal x70=((2.0)*x66);
IkReal x71=((0.020798)*x66);
IkReal x72=((0.020798)*x65);
IkReal x73=((((-1.0)*x39))+(((-1.0)*x55)));
IkReal x74=(x47+x40+x61);
IkReal x75=(x40+x41+x51);
IkReal x76=(x64+x65+x66);
IkReal x77=(x64+(((1.0)*x65))+(((1.0)*x66)));
IkReal x78=(x70+x59+x69);
IkReal x79=(x42+x54+x53+x52);
IkReal x80=(x72+x71+x48+x62);
IkReal x81=((0.1167966)+x78+(((-1.0)*x58)));
IkReal x82=((-0.06079826)+(((-1.0)*x78))+x58);
IkReal x83=((0.06079826)+x78+(((-1.0)*x58)));
IkReal x84=((-0.00479992)+(((-1.0)*x78))+x58);
IkReal x85=((0.139972823724753)+x63+(((-1.0)*x80)));
IkReal x86=((0.0030085096570868)+(((0.054389827916356)*x38))+(((-0.45028084)*x65))+(((-0.45028084)*x66))+(((-0.01039000524258)*x39))+(((-0.11199668)*pz)));
IkReal x87=((0.0828207657978828)+(((0.056902037054556)*x38))+(((-0.65159676)*pz))+(((-0.01086990869358)*x39))+(((-0.47107884)*x65))+(((-0.47107884)*x66)));
IkReal x88=((0.0390079483530608)+(((-0.130357558606544)*x38))+(((0.02490200409192)*x39))+(((1.07920016)*x66))+(((1.07920016)*x65))+(((-0.041596)*pz)));
IkReal x89=((-0.0768037464837092)+(((0.051877618778156)*x38))+(((0.4276034)*pz))+(((-0.00991010179158)*x39))+(((-0.42948284)*x66))+(((-0.42948284)*x65)));
IkReal x90=((-0.0196516885568392)+x80+(((-1.0)*x63)));
IkReal x91=((((0.1167966)*x65))+(((0.1167966)*x66))+x79+(((0.0026950231467)*x39)));
IkReal x92=((((0.00479992)*x66))+(((0.00479992)*x65))+(((0.00011075575404)*x39))+x79);
IkReal x93=((-0.0485518809425512)+x75+(((-1.0)*x91)));
IkReal x94=((-0.0815214504061112)+x75+(((-1.0)*x91)));
IkReal x95=((-0.119963547954854)+(((-1.0)*x79))+(((0.53370282)*pz))+(((0.046697356082576)*x38))+(((-0.38659664)*x65))+(((-0.38659664)*x66))+x40+(((-0.00892052416968)*x39)));
IkReal x96=((-0.08300998417881)+(((-1.0)*x79))+(((0.15300344)*x65))+(((0.15300344)*x66))+x40+(((0.51290482)*pz))+(((-0.018481423220696)*x38))+(((0.00353047787628)*x39)));
IkReal x97=((0.0219813537969652)+x74+(((-1.0)*x92)));
IkReal x98=((-0.0109882156665948)+x74+(((-1.0)*x92)));
IkReal x99=((-0.0299263390388072)+(((0.00611474526894)*x39))+(((-1.0)*x79))+(((0.26500012)*x66))+(((0.26500012)*x65))+(((0.06262398)*pz))+x40+(((-0.032009602994908)*x38)));
IkReal x100=((-0.031980723615824)+(((-0.27459996)*x65))+(((-0.27459996)*x66))+(((-0.00633625677702)*x39))+(((-1.0)*x79))+(((0.033169176308364)*x38))+(((0.08342198)*pz))+x40);
op[0]=x93;
op[1]=-0.0012706390879824;
op[2]=x94;
op[3]=x93;
op[4]=-0.0012706390879824;
op[5]=x94;
op[6]=0;
op[7]=0;
op[8]=0;
op[9]=x95;
op[10]=x95;
op[11]=0;
op[12]=x85;
op[13]=x85;
op[14]=0;
op[15]=x96;
op[16]=x96;
op[17]=0;
op[18]=x67;
op[19]=0;
op[20]=x73;
op[21]=0;
op[22]=x68;
op[23]=0;
op[24]=x73;
op[25]=0;
op[26]=x67;
op[27]=((-0.26685163)+pz);
op[28]=0.1222;
op[29]=((-0.26685119)+pz);
op[30]=0.39200004;
op[31]=8.8e-7;
op[32]=0.14760004;
op[33]=x44;
op[34]=-0.1222;
op[35]=x45;
op[36]=((-0.25439832)+(((-1.0)*x77))+x56);
op[37]=-4.4e-7;
op[38]=((-0.13219832)+(((-1.0)*x77))+x56);
op[39]=-0.01039944;
op[40]=0.2444;
op[41]=-0.01039856;
op[42]=((0.13760172)+(((-1.0)*x77))+x56);
op[43]=4.4e-7;
op[44]=((0.01540172)+(((-1.0)*x77))+x56);
op[45]=((0.26685163)+(((-1.0)*x43)));
op[46]=-0.1222;
op[47]=((0.26685119)+(((-1.0)*x43)));
op[48]=x81;
op[49]=0;
op[50]=x81;
op[51]=x44;
op[52]=-0.1222;
op[53]=x45;
op[54]=x86;
op[55]=0;
op[56]=x86;
op[57]=x86;
op[58]=0;
op[59]=x86;
op[60]=0;
op[61]=0;
op[62]=0;
op[63]=x87;
op[64]=x87;
op[65]=0;
op[66]=x88;
op[67]=x88;
op[68]=0;
op[69]=x89;
op[70]=x89;
op[71]=0;
op[72]=0;
op[73]=x68;
op[74]=0;
op[75]=x68;
op[76]=0;
op[77]=x57;
op[78]=0;
op[79]=x57;
op[80]=0;
op[81]=x82;
op[82]=0;
op[83]=x82;
op[84]=0;
op[85]=0;
op[86]=0;
op[87]=x82;
op[88]=0;
op[89]=x82;
op[90]=x46;
op[91]=0;
op[92]=x46;
op[93]=0;
op[94]=0;
op[95]=0;
op[96]=x46;
op[97]=0;
op[98]=x46;
op[99]=x83;
op[100]=0;
op[101]=x83;
op[102]=x60;
op[103]=0;
op[104]=x60;
op[105]=x82;
op[106]=0;
op[107]=x82;
op[108]=x97;
op[109]=-0.0012706390879824;
op[110]=x98;
op[111]=x97;
op[112]=-0.0012706390879824;
op[113]=x98;
op[114]=0;
op[115]=0;
op[116]=0;
op[117]=x99;
op[118]=x99;
op[119]=0;
op[120]=x90;
op[121]=x90;
op[122]=0;
op[123]=x100;
op[124]=x100;
op[125]=0;
op[126]=x73;
op[127]=0;
op[128]=x67;
op[129]=0;
op[130]=x57;
op[131]=0;
op[132]=x67;
op[133]=0;
op[134]=x73;
op[135]=((0.03131177)+(((-1.0)*x43)));
op[136]=0.1222;
op[137]=((0.03131221)+(((-1.0)*x43)));
op[138]=0.39200004;
op[139]=8.8e-7;
op[140]=0.14760004;
op[141]=x49;
op[142]=-0.1222;
op[143]=x50;
op[144]=((-0.19360006)+x76+(((-1.0)*x56)));
op[145]=-4.4e-7;
op[146]=((-0.07140006)+x76+(((-1.0)*x56)));
op[147]=-0.01039944;
op[148]=0.2444;
op[149]=-0.01039856;
op[150]=((0.19839998)+x76+(((-1.0)*x56)));
op[151]=4.4e-7;
op[152]=((0.07619998)+x76+(((-1.0)*x56)));
op[153]=((-0.03131177)+pz);
op[154]=-0.1222;
op[155]=((-0.03131221)+pz);
op[156]=x84;
op[157]=0;
op[158]=x84;
op[159]=x49;
op[160]=-0.1222;
op[161]=x50;
solvedialyticpoly12qep(op,zeror,numroots);
IkReal j1array[16], cj1array[16], sj1array[16], j2array[16], cj2array[16], sj2array[16], j3array[16], cj3array[16], sj3array[16];
int numsolutions = 0;
for(int ij1 = 0; ij1 < numroots; ij1 += 3)
{
IkReal htj1 = zeror[ij1+0], htj2 = zeror[ij1+1], htj3 = zeror[ij1+2];
if(isnan(htj1)||isnan(htj2)||isnan(htj3)){
continue;
}
j1array[numsolutions]=((2.0)*(atan(htj1)));
j2array[numsolutions]=((2.0)*(atan(htj2)));
j3array[numsolutions]=((2.0)*(atan(htj3)));
if(isinf(htj1)){
cj1array[numsolutions] = IKcos(j1array[numsolutions]);
sj1array[numsolutions] = IKsin(j1array[numsolutions]);
}
else{
IkReal x101=htj1*htj1;
CheckValue<IkReal> x102=IKPowWithIntegerCheck(((1.0)+x101),-1);
if(!x102.valid){
continue;
}
cj1array[numsolutions]=((x102.value)*(((1.0)+(((-1.0)*x101)))));
CheckValue<IkReal> x103=IKPowWithIntegerCheck(((1.0)+(htj1*htj1)),-1);
if(!x103.valid){
continue;
}
sj1array[numsolutions]=((2.0)*htj1*(x103.value));
}
if(isinf(htj2)){
cj2array[numsolutions] = IKcos(j2array[numsolutions]);
sj2array[numsolutions] = IKsin(j2array[numsolutions]);
}
else{
IkReal x104=htj2*htj2;
CheckValue<IkReal> x105=IKPowWithIntegerCheck(((1.0)+x104),-1);
if(!x105.valid){
continue;
}
cj2array[numsolutions]=((x105.value)*(((1.0)+(((-1.0)*x104)))));
CheckValue<IkReal> x106=IKPowWithIntegerCheck(((1.0)+(htj2*htj2)),-1);
if(!x106.valid){
continue;
}
sj2array[numsolutions]=((2.0)*htj2*(x106.value));
}
if(isinf(htj3)){
cj3array[numsolutions] = IKcos(j3array[numsolutions]);
sj3array[numsolutions] = IKsin(j3array[numsolutions]);
}
else{
IkReal x107=htj3*htj3;
CheckValue<IkReal> x108=IKPowWithIntegerCheck(((1.0)+x107),-1);
if(!x108.valid){
continue;
}
cj3array[numsolutions]=((x108.value)*(((1.0)+(((-1.0)*x107)))));
CheckValue<IkReal> x109=IKPowWithIntegerCheck(((1.0)+(htj3*htj3)),-1);
if(!x109.valid){
continue;
}
sj3array[numsolutions]=((2.0)*htj3*(x109.value));
}
if( j1array[numsolutions] > IKPI )
{
    j1array[numsolutions]-=IK2PI;
}
else if( j1array[numsolutions] < -IKPI )
{
    j1array[numsolutions]+=IK2PI;
}
if( j2array[numsolutions] > IKPI )
{
    j2array[numsolutions]-=IK2PI;
}
else if( j2array[numsolutions] < -IKPI )
{
    j2array[numsolutions]+=IK2PI;
}
if( j3array[numsolutions] > IKPI )
{
    j3array[numsolutions]-=IK2PI;
}
else if( j3array[numsolutions] < -IKPI )
{
    j3array[numsolutions]+=IK2PI;
}
numsolutions++;
}
bool j1valid[16]={true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true};
_nj1 = 16;
_nj2 = 1;
_nj3 = 1;
for(int ij1 = 0; ij1 < numsolutions; ++ij1)
    {
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
_ij2[0] = 0; _ij2[1] = -1;
_ij3[0] = 0; _ij3[1] = -1;
for(int iij1 = ij1+1; iij1 < numsolutions; ++iij1)
{
if( !j1valid[iij1] ) { continue; }
if( IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(cj2array[ij1]-cj2array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj2array[ij1]-sj2array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(cj3array[ij1]-cj3array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj3array[ij1]-sj3array[iij1]) < IKFAST_SOLUTION_THRESH &&  1 )
{
    j1valid[iij1]=false; _ij1[1] = iij1; _ij2[1] = 0; _ij3[1] = 0;  break; 
}
}
    j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];

    j2 = j2array[ij1]; cj2 = cj2array[ij1]; sj2 = sj2array[ij1];

    j3 = j3array[ij1]; cj3 = cj3array[ij1]; sj3 = sj3array[ij1];

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(5);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
vinfos[3].jointtype = 1;
vinfos[3].foffset = j3;
vinfos[3].indices[0] = _ij3[0];
vinfos[3].indices[1] = _ij3[1];
vinfos[3].maxsolutions = _nj3;
vinfos[4].jointtype = 1;
vinfos[4].foffset = j4;
vinfos[4].indices[0] = _ij4[0];
vinfos[4].indices[1] = _ij4[1];
vinfos[4].maxsolutions = _nj4;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
    }
}
}
}
return solutions.GetNumSolutions()>0;
}

/// \brief Solve the det Ax^2+Bx+C = 0 problem using the Manocha and Canny method (1994)
///
/// matcoeffs is of length 54*3, for 3 matrices
static inline void solvedialyticpoly12qep(const IkReal* matcoeffs, IkReal* rawroots, int& numroots)
{
    const IkReal tol = 128.0*std::numeric_limits<IkReal>::epsilon();
    IkReal IKFAST_ALIGNED16(M[24*24]) = {0};
    IkReal IKFAST_ALIGNED16(A[12*12]);
    IkReal IKFAST_ALIGNED16(work[24*24*23]);
    int ipiv[12];
    int info, coeffindex;
    const int worksize=24*24*23;
    const int matrixdim = 12;
    const int matrixdim2 = 24;
    numroots = 0;
    // first setup M = [0 I; -C -B] and A
    coeffindex = 0;
    for(int j = 0; j < 6; ++j) {
        for(int k = 0; k < 9; ++k) {
            M[matrixdim+(j+6)+2*matrixdim*k] = M[matrixdim+j+2*matrixdim*(k+3)] = -matcoeffs[coeffindex++];
        }
    }
    for(int j = 0; j < 6; ++j) {
        for(int k = 0; k < 9; ++k) {
            M[matrixdim+(j+6)+2*matrixdim*k+matrixdim*2*matrixdim] = M[matrixdim+j+2*matrixdim*(k+3)+matrixdim*2*matrixdim] = -matcoeffs[coeffindex++];
        }
    }
    for(int j = 0; j < 6; ++j) {
        for(int k = 0; k < 9; ++k) {
            A[(j+6)+matrixdim*k] = A[j+matrixdim*(k+3)] = matcoeffs[coeffindex++];
        }
        for(int k = 0; k < 3; ++k) {
            A[j+matrixdim*k] = A[(j+6)+matrixdim*(k+9)] = 0;
        }
    }
    const IkReal lfpossibilities[4][4] = {{1,-1,1,1},{1,0,-2,1},{1,1,2,0},{1,-1,4,1}};
    int lfindex = -1;
    bool bsingular = true;
    do {
        dgetrf_(&matrixdim,&matrixdim,A,&matrixdim,&ipiv[0],&info);
        if( info == 0 ) {
            bsingular = false;
            for(int j = 0; j < matrixdim; ++j) {
                if( IKabs(A[j*matrixdim+j]) < 100*tol ) {
                    bsingular = true;
                    break;
                }
            }
            if( !bsingular ) {
                break;
            }
        }
        if( lfindex == 3 ) {
            break;
        }
        // transform by the linear functional
        lfindex++;
        const IkReal* lf = lfpossibilities[lfindex];
        // have to reinitialize A
        coeffindex = 0;
        for(int j = 0; j < 6; ++j) {
            for(int k = 0; k < 9; ++k) {
                IkReal a = matcoeffs[coeffindex+108], b = matcoeffs[coeffindex+54], c = matcoeffs[coeffindex];
                A[(j+6)+matrixdim*k] = A[j+matrixdim*(k+3)] = lf[0]*lf[0]*a+lf[0]*lf[2]*b+lf[2]*lf[2]*c;
                M[matrixdim+(j+6)+2*matrixdim*k] = M[matrixdim+j+2*matrixdim*(k+3)] = -(lf[1]*lf[1]*a + lf[1]*lf[3]*b + lf[3]*lf[3]*c);
                M[matrixdim+(j+6)+2*matrixdim*k+matrixdim*2*matrixdim] = M[matrixdim+j+2*matrixdim*(k+3)+matrixdim*2*matrixdim] = -(2*lf[0]*lf[1]*a + (lf[0]*lf[3]+lf[1]*lf[2])*b + 2*lf[2]*lf[3]*c);
                coeffindex++;
            }
            for(int k = 0; k < 3; ++k) {
                A[j+matrixdim*k] = A[(j+6)+matrixdim*(k+9)] = 0;
            }
        }
    } while(lfindex<4);

    if( bsingular ) {
        return;
    }
    dgetrs_("No transpose", &matrixdim, &matrixdim2, A, &matrixdim, &ipiv[0], &M[matrixdim], &matrixdim2, &info);
    if( info != 0 ) {
        return;
    }

    // set identity in upper corner
    for(int j = 0; j < matrixdim; ++j) {
        M[matrixdim*2*matrixdim+j+matrixdim*2*j] = 1;
    }
    IkReal IKFAST_ALIGNED16(wr[24]);
    IkReal IKFAST_ALIGNED16(wi[24]);
    IkReal IKFAST_ALIGNED16(vr[24*24]);
    int one=1;
    dgeev_("N", "V", &matrixdim2, M, &matrixdim2, wr, wi,NULL, &one, vr, &matrixdim2, work, &worksize, &info);
    if( info != 0 ) {
        return;
    }
    IkReal Breal[matrixdim-1];
    for(int i = 0; i < matrixdim2; ++i) {
        if( IKabs(wi[i]) < tol*100 ) {
            IkReal* ev = vr+matrixdim2*i;
            if( IKabs(wr[i]) > 1 ) {
                ev += matrixdim;
            }
            // consistency has to be checked!!
            if( IKabs(ev[0]) < tol ) {
                continue;
            }
            IkReal iconst = 1/ev[0];
            for(int j = 1; j < matrixdim; ++j) {
                Breal[j-1] = ev[j]*iconst;
            }
            if( checkconsistency12(Breal) ) {
                if( lfindex >= 0 ) {
                    const IkReal* lf = lfpossibilities[lfindex];
                    rawroots[numroots++] = (wr[i]*lf[0]+lf[1])/(wr[i]*lf[2]+lf[3]);
                }
                else {
                    rawroots[numroots++] = wr[i];
                }
                bool bsmall0=IKabs(ev[0]) > IKabs(ev[3]);
                bool bsmall1=IKabs(ev[0]) > IKabs(ev[1]);
                if( bsmall0 && bsmall1 ) {
                    rawroots[numroots++] = ev[3]/ev[0];
                    rawroots[numroots++] = ev[1]/ev[0];
                }
                else if( bsmall0 && !bsmall1 ) {
                    rawroots[numroots++] = ev[5]/ev[2];
                    rawroots[numroots++] = ev[2]/ev[1];
                }
                else if( !bsmall0 && bsmall1 ) {
                    rawroots[numroots++] = ev[9]/ev[6];
                    rawroots[numroots++] = ev[10]/ev[9];
                }
                else if( !bsmall0 && !bsmall1 ) {
                    rawroots[numroots++] = ev[11]/ev[8];
                    rawroots[numroots++] = ev[11]/ev[10];
                }
            }
        }
    }
}
static inline bool checkconsistency12(const IkReal* Breal)
{
    IkReal norm = 0.1;
    for(int i = 0; i < 11; ++i) {
        norm += IKabs(Breal[i]);
    }
    IkReal tol = 1e-6*norm; // have to increase the threshold since many computations are involved
    return IKabs(Breal[0]*Breal[0]-Breal[1]) < tol && IKabs(Breal[0]*Breal[2]-Breal[3]) < tol && IKabs(Breal[1]*Breal[2]-Breal[4]) < tol && IKabs(Breal[2]*Breal[2]-Breal[5]) < tol && IKabs(Breal[0]*Breal[5]-Breal[6]) < tol && IKabs(Breal[1]*Breal[5]-Breal[7]) < tol && IKabs(Breal[2]*Breal[5]-Breal[8]) < tol && IKabs(Breal[0]*Breal[8]-Breal[9]) < tol && IKabs(Breal[1]*Breal[8]-Breal[10]) < tol;
}
};


/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API bool ComputeIk2(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions, void* pOpenRAVEManip) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API const char* GetKinematicsHash() { return "f6b430eb44e3ee055aa4ae875eceeb8e"; }

IKFAST_API const char* GetIkFastVersion() { return "0x10000049"; }

#ifdef IKFAST_NAMESPACE
} // end namespace
#endif

#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>
#ifdef IKFAST_NAMESPACE
using namespace IKFAST_NAMESPACE;
#endif
int main(int argc, char** argv)
{
    if( argc != 12+GetNumFreeParameters()+1 ) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",GetNumFreeParameters());
        return 1;
    }

    IkSolutionList<IkReal> solutions;
    std::vector<IkReal> vfree(GetNumFreeParameters());
    IkReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    for(std::size_t i = 0; i < vfree.size(); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ComputeIk(eetrans, eerot, vfree.size() > 0 ? &vfree[0] : NULL, solutions);

    if( !bSuccess ) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }

    printf("Found %d ik solutions:\n", (int)solutions.GetNumSolutions());
    std::vector<IkReal> solvalues(GetNumJoints());
    for(std::size_t i = 0; i < solutions.GetNumSolutions(); ++i) {
        const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
        printf("sol%d (free=%d): ", (int)i, (int)sol.GetFree().size());
        std::vector<IkReal> vsolfree(sol.GetFree().size());
        sol.GetSolution(&solvalues[0],vsolfree.size()>0?&vsolfree[0]:NULL);
        for( std::size_t j = 0; j < solvalues.size(); ++j)
            printf("%.15f, ", solvalues[j]);
        printf("\n");
    }
    return 0;
}

#endif
