# Default initial positions for so101_new_calib's ros2_control fake system

initial_positions:
  left_1: 0
  left_2: 0
  left_3: 0
  left_4: 0
  left_5: 0
  left_6: 0
  right_1: 0
  right_2: 0
  right_3: 0
  right_4: 0
  right_5: 0
  right_6: 0