# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_gripper_controller
    - right_gripper_controller
    - arms_controller

  left_gripper_controller:
    type: GripperCommand
    joints:
      - left_6
    action_ns: gripper_cmd
    default: true
  right_gripper_controller:
    type: GripperCommand
    joints:
      - right_6
    action_ns: gripper_cmd
    default: true
  arms_controller:
    type: FollowJointTrajectory
    joints:
      - left_1
      - left_2
      - left_3
      - left_4
      - left_5
      - right_1
      - right_2
      - right_3
      - right_4
      - right_5
    action_ns: follow_joint_trajectory
    default: True