# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_gripper_controller:
      type: position_controllers/GripperActionController


    right_gripper_controller:
      type: position_controllers/GripperActionController


    arms_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_gripper_controller:
  ros__parameters:
    joint: left_6
right_gripper_controller:
  ros__parameters:
    joint: right_6
arms_controller:
  ros__parameters:
    joints:
      - left_1
      - left_2
      - left_3
      - left_4
      - left_5
      - right_1
      - right_2
      - right_3
      - right_4
      - right_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity