left_arm:
  kinematics_solver: so101_new_calib_left_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.50000000000000001
right_arm:
  kinematics_solver: so101_new_calib_right_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.50000000000000001