# Default initial positions for panda's ros2_control fake system

initial_positions:
  left_panda_finger_joint1: 0
  left_panda_joint1: 0
  left_panda_joint2: -1.0
  left_panda_joint3: 0
  left_panda_joint4: -1.2
  left_panda_joint5: 0
  left_panda_joint6: 0.2
  left_panda_joint7: 0
  right_panda_finger_joint1: 0
  right_panda_joint1: 0
  right_panda_joint2: -1.0
  right_panda_joint3: 0
  right_panda_joint4: -1.2
  right_panda_joint5: 0
  right_panda_joint6: 0.2
  right_panda_joint7: 0